apiVersion: v1
kind: Secret
metadata:
  name: alert-route-example
  namespace: default
  labels:
    alert_route: "1"
type: Opaque
stringData:
  name: ops
  contacts: ops
  match_namespaces: |
    namespaces: all
  keys: |
    opsgenie: "api-key-long"
    chat: "long-webhook"
  transform: |
    [
      {
        "grafana_annotation": "k8s_namespace",
        "dashboard_url": "https://grafana.example.local/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=thanos",
        "labels": [
          "namespace",
          "cluster"
        ]
      },
      {
        "grafana_annotation": "k8s_pods",
        "dashboard_url": "https://grafana.example.local/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?orgId=1&var-datasource=thanos",
        "labels": [
          "namespace",
          "cluster",
          "pod"
        ]
      }
    ]